### ISSUE TITLE
There is something wrong about the provided pretrained vgg-model

### ISSUE THREAD

**Issue by yuxijin** [diyiiyiii/Arbitrary-Style-Transfer-via-Multi-Adaptation-Network#1]
The file downloaded via the provided pretrained vgg-model is named 'decoder_iter_160000.pth', but the test.py code refers vgg_path to './model/vgg_normalised.pth'. Where to get the 'vgg_normalised.pth'? Is the file provided by the pretrained model provided link wrong?

**Comment by diyiiyiii** [comment]
We have already updated the link.

**Comment by yuxijin** [comment]
> We have already updated the link.

Thank you very much~
