### ISSUE TITLE
请问能提供一下关于视频风格的代码吗？

### ISSUE THREAD

**Issue by fengxiaoming520** [diyiiyiii/Arbitrary-Style-Transfer-via-Multi-Adaptation-Network#8]
请问对于视频风格迁移也是使用test.py文件进行测试吗？

**Comment by diyiiyiii** [comment]
不是的，你可以参照https://github.com/diyiiyiii/MCCNet中的test_video.py修改

**Comment by fengxiaoming520** [comment]
按您说的通过修改MCCNet的测试代码来进行视频上测试，但得到的测试结果并没有MCCNet得到的结果好，MANet的结果具有非常明显的闪烁。

**Comment by diyiiyiii** [comment]
这篇文章不适合处理视频，因为没有考虑视频连续性，所以结果确实比较闪烁。

**Comment by fengxiaoming520** [comment]
好的，感谢您的解答！
